### ISSUE TITLE
Enhanced Parsing Strategy: Structured Data Models & RDF Mapper

### ISSUE THREAD

**Issue by JonasHeinickeBio** [JonasHeinickeBio/pyEuropePMC#15]
Here’s a polished, copy-pasteable GitHub issue tailored to **your current parser module** and focused on **Data Models + RDF mapping** with a **base class + inheritance** design.

---

## 🚀 Issue #15 — Data Models & RDF Mapping for Full-Text XML Parser

**Status:** Open
**Owner:** @JonasHeinickeBio
**Priority:** P1
**Milestone:** Schema & Parsing (Phase 1 → 2)
**Scope:** Implement typed data models that directly wrap the outputs of `FullTextXMLParser` and serialize to RDF using a central mapping.

---

### 🎯 Summary

We have a robust `FullTextXMLParser` that extracts:

* metadata (`extract_metadata`),
* authors (`extract_authors` / `extract_affiliations`),
* sections (`get_full_text_sections`),
* tables (`extract_tables`), and
* references (`extract_references`).

This issue introduces a **typed data model layer** with **inheritance** and a **generic RDF mapper** so every parsed object can be:

* validated and normalized,
* exported to JSON/JSON-LD,
* exported to RDF (TTL) aligned to our ontology (AID-PAIS + BIBO/FOAF/PROV, etc.),
* SHACL-validated in GraphDB.

---

#### 1) Base class

```python
# models/base.py
from dataclasses import dataclass, field, asdict
from typing import Optional, Dict, Any, List
from rdflib import Graph, URIRef, Literal, Namespace
import uuid

AID  = Namespace("http://aid-pais.org/ontology#")
DATA = Namespace("http://aid-pais.org/data/")
DCT  = Namespace("http://purl.org/dc/terms/")
RDFS = Namespace("http://www.w3.org/2000/01/rdf-schema#")
PROV = Namespace("http://www.w3.org/ns/prov#")

@dataclass
class BaseEntity:
    id: Optional[str] = None                # local identifier (slug/uuid)
    label: Optional[str] = None
    source_uri: Optional[str] = None        # e.g., PMC XML file IRI
    confidence: Optional[float] = None
    types: List[str] = field(default_factory=list)  # RDF types (CURIEs/URIs)

    def mint_uri(self, path: str) -> URIRef:
        _id = self.id or str(uuid.uuid4())
        return URIRef(f"{DATA}{path}/{_id}")

    def validate(self) -> None:
        # Override in subclasses; raise ValueError on critical issues
        pass

    def normalize(self) -> None:
        # Override in subclasses; e.g., lowercase DOI, trim whitespace
        pass

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    def to_rdf(self, g: Graph, uri: Optional[URIRef] = None, mapper=None) -> URIRef:
        """
        Generic serialization using a mapper (conf/rdf_map.yml).
        """
        if mapper is None:
            raise ValueError("RDF mapper required")
        subject = uri or self.mint_uri(self.__class__.__name__.lower())
        mapper.add_types(g, subject, self.types)
        mapper.map_fields(g, subject, self)  # uses conf/rdf_map.yml + dataclass fields
        if self.source_uri:
            g.add((subject, PROV.wasDerivedFrom, URIRef(self.source_uri)))
        if self.label:
            g.add((subject, RDFS.label, Literal(self.label)))
        if self.confidence is not None:
            g.add((subject, AID.confidence, Literal(self.confidence)))
        return subject
```

#### 2) Subclasses (inheritance)

* `AuthorEntity` — wraps `extract_authors()` + `extract_affiliations()`
* `PaperEntity` — wraps `extract_metadata()`
* `SectionEntity` — wraps `get_full_text_sections()` items
* `TableEntity` & `TableRowEntity` — wrap `extract_tables()`
* `ReferenceEntity` — wraps `extract_references()`
* (Optional) `DocumentSchemaEntity` — wraps `detect_schema()`

Example:

```python
# models/author.py
from dataclasses import dataclass
from typing import Optional
from .base import BaseEntity

@dataclass
class AuthorEntity(BaseEntity):
    full_name: str = ""
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    initials: Optional[str] = None
    affiliation_text: Optional[str] = None
    orcid: Optional[str] = None
    # types pre-populated for mapper
    def __post_init__(self):
        self.types = self.types or ["foaf:Person"]
        self.label = self.label or self.full_name
```

```python
# models/paper.py
from dataclasses import dataclass
from typing import Optional, List
from .base import BaseEntity

@dataclass
class PaperEntity(BaseEntity):
    pmcid: Optional[str] = None
    doi: Optional[str] = None
    title: Optional[str] = None
    journal: Optional[str] = None
    volume: Optional[str] = None
    issue: Optional[str] = None
    pages: Optional[str] = None
    pub_date: Optional[str] = None
    keywords: List[str] = None
    def __post_init__(self):
        self.types = self.types or ["bibo:AcademicArticle"]
        self.label = self.label or (self.title or self.doi or self.pmcid)
    def normalize(self):
        if self.doi:
            self.doi = self.doi.lower().replace("https://doi.org/", "").strip()
```

(Analogous small classes for `SectionEntity`, `TableEntity`, `ReferenceEntity`.)

---

### 🗺️ RDF Mapping (YAML-driven)

Create **`conf/rdf_map.yml`** to keep code clean and allow future changes without edits:

```yaml
# BaseEntity defaults
_@prefix:
  aid:  "http://aid-pais.org/ontology#"
  dct:  "http://purl.org/dc/terms/"
  foaf: "http://xmlns.com/foaf/0.1/"
  bibo: "http://purl.org/ontology/bibo/"
  prov: "http://www.w3.org/ns/prov#"
  rdfs: "http://www.w3.org/2000/01/rdf-schema#"
  nif:  "http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#"

PaperEntity:
  rdf:type: ["bibo:AcademicArticle"]
  fields:
    pmcid: dct:identifier
    doi:   bibo:doi
    title: dct:title
    journal: bibo:Journal
    volume: bibo:volume
    issue:  bibo:issue
    pages:  bibo:pages
    pub_date: dct:issued
  links:
    authors: aid:hasAuthor      # expects URIRefs of AuthorEntity
    sections: dct:hasPart       # SectionEntity URIs
    tables:   dct:hasPart       # TableEntity URIs
    references: bibo:cites      # ReferenceEntity URIs

AuthorEntity:
  rdf:type: ["foaf:Person"]
  fields:
    full_name: foaf:name
    first_name: foaf:givenName
    last_name:  foaf:familyName
    initials:   bibo:shortTitle
    orcid:      bibo:identifier
    affiliation_text: dct:publisher  # or org:memberOf if structured later

SectionEntity:
  rdf:type: ["bibo:DocumentPart", "nif:Context"]
  fields:
    title: dct:title
    content: nif:isString
  # Optional NIF offsets if sentence splitter later adds them
  # fields: beginIndex: nif:beginIndex, endIndex: nif:endIndex

TableEntity:
  rdf:type: ["bibo:Table"]
  fields:
    label: rdfs:label
    caption: dct:description
  links:
    rows: dct:hasPart

TableRowEntity:
  rdf:type: ["bibo:Row"]
  fields:
    headers: aid:hasHeader          # serialize list as multiple triples
    cells:   aid:hasCell            # serialize list as multiple triples

ReferenceEntity:
  rdf:type: ["bibo:Document"]
  fields:
    label: rdfs:label
    title: dct:title
    source: dct:isPartOf
    year: dct:issued
    volume: bibo:volume
    pages: bibo:pages
    doi: bibo:doi
```

Implement a small **`rdf_mapper.py`** that:

* loads `conf/rdf_map.yml`,
* resolves prefixes,
* iterates dataclass `__dict__`,
* adds `(subject, predicate, object)` triples for scalar or list fields,
* supports `links` for relations (expects URIs),
* sets `rdf:type` from `rdf:type`.

---

### 🔗 Integration points with the parser

Add a light **builder layer** that converts parser outputs → entities:

```python
# builders/from_parser.py
from models import PaperEntity, AuthorEntity, SectionEntity, TableEntity, TableRowEntity, ReferenceEntity

def build_paper_entities(parser: "FullTextXMLParser"):
    meta = parser.extract_metadata()
    paper = PaperEntity(
        id=meta.get("pmcid") or meta.get("doi"),
        label=meta.get("title"),
        source_uri="urn:pmc:" + (meta.get("pmcid") or ""),
        pmcid=meta.get("pmcid"),
        doi=meta.get("doi"),
        title=meta.get("title"),
        journal=meta.get("journal"),
        volume=meta.get("volume"),
        issue=meta.get("issue"),
        pages=meta.get("pages"),
        pub_date=meta.get("pub_date"),
        keywords=meta.get("keywords") or [],
    )

    authors = [AuthorEntity(full_name=a) for a in (meta.get("authors") or [])]
    sections = [SectionEntity(label=s["title"], title=s["title"], content=s["content"]) 
                for s in parser.get_full_text_sections()]
    tables = []
    for t in parser.extract_tables():
        te = TableEntity(label=t.get("label"), caption=t.get("caption"))
        # optional: add rows as TableRowEntity
        tables.append(te)
    refs = [ReferenceEntity(**r) for r in parser.extract_references()]

    return paper, authors, sections, tables, refs
```

---

### ✅ Acceptance Criteria

* **Models**

  * [ ] Implement `BaseEntity` + subclasses: `PaperEntity`, `AuthorEntity`, `SectionEntity`, `TableEntity`, `TableRowEntity`, `ReferenceEntity`.
  * [ ] Each subclass has `validate()` + `normalize()` (e.g., DOI cleanup).

* **RDF Mapper**

  * [ ] `rdf_mapper.py` loads `conf/rdf_map.yml`, supports `fields` and `links`.
  * [ ] `to_rdf()` on all entities yields triples with correct predicates and types.
  * [ ] Multi-value fields emit multiple triples.
  * [ ] URIs minted under `http://aid-pais.org/data/<type>/<id>`.

* **Integration**

  * [ ] `builders/from_parser.py` converts parser outputs to entities.
  * [ ] CLI script `scripts/xml_to_rdf.py`:

    ```
    xml_to_rdf.py input.xml --ttl out.ttl --json out.json
    ```
  * [ ] SHACL validation passes (supply minimal shapes for Paper, Author, Section, Table, Reference).

* **Tests**

  * [ ] Unit tests: each entity `.to_rdf()` produces expected triples.
  * [ ] Round-trip JSON → RDF → (spot checks) retains values.
  * [ ] Parser → builder pipeline works on 2–3 fixture XMLs.

* **Docs**

  * [ ] `docs/models.md` with class diagrams and example TTL.
  * [ ] `conf/rdf_map.yml` fully documented (prefixes, fields, links).

---

### 🧪 SHACL (minimal starter)

Create `shacl/pub.shacl.ttl`:

```turtle
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix bibo: <http://purl.org/ontology/bibo/> .
@prefix dct: <http://purl.org/dc/terms/> .

bibo:AcademicArticleShape a sh:NodeShape ;
  sh:targetClass bibo:AcademicArticle ;
  sh:property [ sh:path dct:title ; sh:minCount 1 ] ;
  sh:property [ sh:path dct:issued ; sh:minCount 0 ] ;
  sh:property [ sh:path dct:identifier ; sh:minCount 0 ] .
```

(Add shapes for Person/Section/Table later.)

---

### 🗂️ File layout

```
models/
  base.py
  author.py
  paper.py
  section.py
  table.py
  reference.py
mappers/
  rdf_mapper.py
builders/
  from_parser.py
conf/
  rdf_map.yml
shacl/
  pub.shacl.ttl
scripts/
  xml_to_rdf.py
tests/
  test_models_rdf.py
  fixtures/pmc_example.xml
```

---

### 🧭 Notes / Next Steps

* add **NIF sentence spans** to `SectionEntity` (begin/end offsets) and map to `nif:Context`/`nif:isString`.
* When affiliations are structured, switch `affiliation_text → org:memberOf` with `Organization` entities.
* Add `ObservationEntity` in a next issue to represent extracted mechanistic statements (subject–predicate–object with qualifiers + provenance).

---
